#####################################
# Settings
#####################################

datasource:
  # driverClassName: org.h2.Driver
  driverClassName: org.postgresql.Driver
  # driverClassName: com.mysql.jdbc.Driver
  # url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  url: "jdbc:postgresql://localhost:5432/test_db"
  schema: public
  username: root
  password: password

outputDirectory: "./.dist"
