version: '3'
services:
  postgresql:
    image: "postgres:9.6"
    container_name: "postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    tty: true
    restart: always
    user: root
    volumes:
      - ./postgresql-init:/docker-entrypoint-initdb.d
#      - test_db:/var/lib/postgresql/data
#      - /etc/localtime:/etc/localtime:ro

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
